### ISSUE TITLE
GENERATE_SOURCEMAP not recognized

### ISSUE THREAD

**Issue by damip** [massalabs/create-react-app-massa#6]
A student had the following error: 

![20221120_044941](https://user-images.githubusercontent.com/10211103/203015368-04170435-1636-4b0c-b719-44294ab188cc.jpg)

When he removed the GENERATE_SOURCEMAP=false, everything worked normally.

**Comment by BatiGencho** [comment]
Should be fixed in https://github.com/massalabs/create-react-app-massa/pull/7

**Comment by BatiGencho** [comment]
as confirmed, it has been tested on WIndows. I have merged the MR and am releasing a new verison!

**Comment by damip** [comment]
> as confirmed, it has been tested on WIndows. I have merged the MR and am releasing a new verison!

super ! feel free to close this issue it it is corrected
